### ISSUE TITLE
[PE-D][Tester E] Discrepancies in tag field constraints

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-3/tp#235]
## Reference Screenshot - Entering an edit command with invalid tag
![Screenshot 2024-04-05 175124.png](https://raw.githubusercontent.com/triciiaaa/ped/main/files/041e46ef-14ce-49cc-826e-3f141851380f.png)

## Reference Screenshot - Command constraints for tag field in User Guide
![Screenshot 2024-04-05 175336.png](https://raw.githubusercontent.com/triciiaaa/ped/main/files/8ede7172-d083-40ea-a0d2-75f140853fb8.png)

## Description
After keying in an invalid tag, the error message displayed states that the tag cannot be blank. However, the User Guide mentions that the tags can be removed without inputting any strings behind the prefix.

Additionally, the first part of the error message is incorrect as my input did not contain any additional '\\' aside from the one used for the prefix. Instead, the character causing the error should be '*'.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: triciiaaa/ped#14

**Comment by aureliony** [comment]
The error message covers 3 different possible cases of invalid inputs: `\`, `only alphabets and numbers`, and `should not be blank`.
In this case, it falls under `only alphabets and numbers` since `*` is neither an alphabet or a number.
We should split the error message into 3 lines, and add a remark indicating that all 3 cases must be satisfied to make it clearer to the user.
